// Code generated by sqlc. DO NOT EDIT.
// source: account.sql

package db

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO account (
  owner, 
  balance,
  courrency
) VALUES (
  $1, $2,$3
)
RETURNING id, owner, balance, courrency, created_at
`

type CreateAccountParams struct {
	Owner     string  `json:"owner"`
	Balance   float64 `json:"balance"`
	Courrency string  `json:"courrency"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount, arg.Owner, arg.Balance, arg.Courrency)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.Courrency,
		&i.CreatedAt,
	)
	return i, err
}
